"""
response.py — Safe, Human-in-the-Loop Response Engine.
Generates firewall RECOMMENDATIONS as downloadable scripts.
NEVER auto-executes. Returns script text + recommendation list.
"""
import re

SEVERITY_RECOMMENDATIONS = {
    "CRITICAL": [
        "IMMEDIATELY isolate the affected host from the network segment.",
        "Contact the incident response team and escalate to P1 severity.",
        "Preserve all volatile memory and logs for forensic analysis.",
        "Review all authentication events for the attacker IP in last 72 hours.",
    ],
    "HIGH": [
        "Block the identified attacker IP at the perimeter firewall.",
        "Force password reset for any accounts accessed from this IP.",
        "Enable enhanced logging on affected services for 48 hours.",
        "Conduct a vulnerability assessment of the targeted service.",
    ],
    "MEDIUM": [
        "Monitor the identified IP for continued suspicious activity.",
        "Review access policies and enforce principle of least privilege.",
        "Enable multi-factor authentication if not already configured.",
    ],
    "LOW": [
        "Log and monitor this activity for recurrence.",
        "No immediate action required; update threat intelligence feed.",
    ]
}

def generate_defense_script(attacker_ip: str, severity: str, threat_type: str) -> str:
    """
    Generates a Linux iptables + Windows netsh firewall remediation script.
    This is a RECOMMENDATION only — the user must download and manually execute.
    Returns script as plain text string.
    """
    if not attacker_ip:
        return "# No specific attacker IP identified.\n# Apply general hardening recommendations."
    
    if severity not in ("CRITICAL", "HIGH"):
        return f"# Severity {severity}: Firewall blocking not recommended for this level.\n# Monitor {attacker_ip} for continued activity."
    
    return f"""#!/bin/bash
# =============================================================
# 🛡️  SOC INCIDENT RESPONSE PLAYBOOK — GENERATED BY SOC SYSTEM
# =============================================================
# Threat Type : {threat_type}
# Severity    : {severity}
# Hostile IP  : {attacker_ip}
# Generated   : $(date -u)
#
# ⚠️  HUMAN-IN-THE-LOOP POLICY:
# This script is a RECOMMENDATION generated by the AI engine.
# Review carefully before executing.
# Run only with root/Administrator privileges.
# =============================================================

echo "[SOC] Initiating containment of {attacker_ip}..."

# ── Linux: iptables Rules ─────────────────────────────────────
if command -v iptables &>/dev/null; then
    iptables -A INPUT  -s {attacker_ip} -j DROP
    iptables -A OUTPUT -d {attacker_ip} -j DROP
    iptables -A FORWARD -s {attacker_ip} -j DROP
    
    # Persist across reboots (Debian/Ubuntu)
    if command -v iptables-save &>/dev/null; then
        iptables-save > /etc/iptables/rules.v4
    fi
    echo "[✓] Linux iptables rule applied for {attacker_ip}"
fi

# ── Linux: UFW (if installed) ─────────────────────────────────
if command -v ufw &>/dev/null; then
    ufw deny from {attacker_ip} to any
    echo "[✓] UFW deny rule applied for {attacker_ip}"
fi

# ── Network: Null-Route the hostile IP ───────────────────────
ip route add blackhole {attacker_ip} 2>/dev/null && \\
    echo "[✓] Null-route blackhole applied for {attacker_ip}"

echo ""
echo "============================================"
echo "  CONTAINMENT COMPLETE: {attacker_ip}"  
echo "  Threat Level: {severity}"
echo "  Document this action in your SIEM/ticketing system."
echo "============================================"
"""

def get_recommendations(severity: str, threats: list) -> list:
    """
    Returns actionable recommendation list based on severity and threat types.
    Merges generic severity-based advice with threat-specific guidance.
    """
    base_recs = SEVERITY_RECOMMENDATIONS.get(severity, SEVERITY_RECOMMENDATIONS["LOW"])
    specific = []
    
    for threat in threats:
        t_type = threat.get("type", "").lower()
        if "sql" in t_type:
            specific.append("Deploy a Web Application Firewall (WAF) with SQLi rule sets.")
            specific.append("Sanitize all user inputs using parameterized queries.")
        elif "ssh" in t_type or "brute" in t_type:
            specific.append("Implement fail2ban or equivalent SSH rate-limiting.")
            specific.append("Restrict SSH access to trusted IP ranges only.")
        elif "c2" in t_type or "command" in t_type:
            specific.append("Block outbound DNS to external resolvers; force internal DNS only.")
            specific.append("Analyze DNS query logs for domain generation algorithm patterns.")
        elif "exfil" in t_type:
            specific.append("Implement Data Loss Prevention (DLP) on outbound traffic.")
            specific.append("Review and restrict egress firewall rules to necessary ports only.")
    
    # Deduplicate
    seen = set()
    combined = []
    for r in base_recs + specific:
        if r not in seen:
            combined.append(r)
            seen.add(r)
    return combined
